name: Generate PDF and EPUB

on:
  push:
    branches:
      - main
    paths:
      - 'chapters/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Pandoc and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-lang-chinese fonts-noto-cjk

    - name: Concatenate Markdown files
      run: |
        cd chapters
        cat > ../combined.md << 'EOF'
        ---
        title: "智能体设计模式"
        subtitle: "构建智能系统实战指南"
        author: "Antonio Gulli"
        documentclass: book
        lang: zh-CN
        CJKmainfont: "Noto Sans CJK SC"
        geometry: "margin=1in"
        ---
        
        EOF
        
        # 按照Agentic Design Patterns.md中定义的顺序拼接章节
        cat "README.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 1_ Prompt Chaining.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 2_ Routing.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 3_ Parallelization.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 4_ Reflection.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 5_ Tool Use.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 6_ Planning.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 7_ Multi-Agent Collaboration.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 8_ Memory Management.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 9_ Learning and Adaptation.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 10_ Model Context Protocol (MCP).md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 11_ Goal Setting and Monitoring.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 12_ Exception Handling and Recovery.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 13_ Human-in-the-Loop.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 14_ Knowledge Retrieval (RAG).md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 15_ Inter-Agent Communication (A2A).md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 16_ Resource-Aware Optimization.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 17_ Reasoning Techniques.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 18_ Guardrails_Safety Patterns.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 19_ Evaluation and Monitoring.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 20_ Prioritization.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Chapter 21_ Exploration and Discovery.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Appendix A_ Advanced Prompting Techniques.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Appendix B - AI Agentic Interactions_ From GUI to Real world environment.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Appendix C - Quick overview of Agentic Frameworks.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Appendix D - Building an Agent with AgentSpace (on-line only).md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Appendix E - AI Agents on the CLI.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Appendix F  - Under the Hood_ An Inside Look at the Agents' Reasoning Engines.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Appendix G -  Coding agents.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Conclusion.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Glossary.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Index of Terms.md" >> ../combined.md
        echo -e "\n\n" >> ../combined.md
        
        cat "Frequently Asked Questions_ Agentic Design Patterns.md" >> ../combined.md

    - name: Generate PDF
      run: |
        pandoc combined.md \
          -o agentic-design-patterns-chinese.pdf \
          --pdf-engine=xelatex \
          --toc \
          --toc-depth=2 \
          -V mainfont="Noto Sans CJK SC" \
          -V geometry:margin=1in \
          --metadata title="智能体设计模式" \
          --metadata author="Antonio Gulli" \
          --metadata lang=zh-CN

    - name: Generate EPUB
      run: |
        pandoc combined.md \
          -o agentic-design-patterns-chinese.epub \
          --toc \
          --toc-depth=2 \
          --metadata title="智能体设计模式" \
          --metadata author="Antonio Gulli" \
          --metadata lang=zh-CN \
          --epub-cover-image=images/cover.png

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: agentic-design-patterns-chinese-pdf
        path: agentic-design-patterns-chinese.pdf

    - name: Upload EPUB artifact
      uses: actions/upload-artifact@v4
      with:
        name: agentic-design-patterns-chinese-epub
        path: agentic-design-patterns-chinese.epub

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: |
          agentic-design-patterns-chinese.pdf
          agentic-design-patterns-chinese.epub
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}